# Derive displacements

In [ ]:
dataset_ver = 3

In [ ]:
from google.colab import drive
import zipfile
import os
import shutil
import numpy as np

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
zip_path = "/content/drive/MyDrive/FYP/datasets/"+str(dataset_ver)+"/BlenderOutputs_Sim.zip"

extract_dir = "/content/dataset"
os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print("✅ Extraction complete. Files are in:", extract_dir)

✅ Extraction complete. Files are in: /content/dataset


In [ ]:
num_of_iterations = 100
frames_per_iteration = 300

In [ ]:
dataset_path = "/content/dataset/BlenderOutputs_Sim"
output_path = "/content/dataset/target"

if os.path.exists(output_path):
    shutil.rmtree(output_path)

os.makedirs(output_path, exist_ok=False)

for i in range (1, num_of_iterations + 1):
  for j in range (1, frames_per_iteration):
    first = np.load(dataset_path + f'/flag_{i:03d}_{j:03d}.npy')
    second = np.load(dataset_path + f'/flag_{i:03d}_{j+1:03d}.npy')
    displacement = second - first
    np.save(output_path + f'/displacement_{i:03d}_{j:03d}.npy', displacement)
print(f"displacements saved to {output_path}")

displacements saved to /content/dataset/target


In [ ]:
shutil.make_archive("displacements", 'zip', output_path)

'/content/displacements.zip'

In [ ]:
first = np.load(dataset_path+'/flag_001_001.npy')
second = np.load(dataset_path+'/flag_001_002.npy')
displacement = np.load(output_path+'/displacement_001_001.npy')

print("First frame (10 vertices):\n", first[:10])
print("\nSecond frame (10 vertices):\n", second[:10])
print("\nDisplacement (10 vertices):\n", displacement[:10])

First frame (10 vertices):
 [[ 3.18441465e-02 -9.99492824e-01 -3.00000012e-01]
 [-1.31067672e-08 -4.17585827e-10 -3.00000012e-01]
 [ 3.18441764e-02 -9.99492824e-01  3.00000012e-01]
 [ 1.31067672e-08  4.17585827e-10  3.00000012e-01]
 [ 3.18441726e-02 -9.99492824e-01  2.80645162e-01]
 [ 3.18441726e-02 -9.99492824e-01  2.61290342e-01]
 [ 3.18441726e-02 -9.99492824e-01  2.41935492e-01]
 [ 3.18441726e-02 -9.99492824e-01  2.22580656e-01]
 [ 3.18441689e-02 -9.99492824e-01  2.03225821e-01]
 [ 3.18441689e-02 -9.99492824e-01  1.83870971e-01]]

Second frame (10 vertices):
 [[ 3.82647403e-02 -9.97611046e-01 -3.05592984e-01]
 [-1.31067690e-08 -4.17585855e-10 -3.00000042e-01]
 [ 3.63806188e-02 -9.98057604e-01  2.93430835e-01]
 [ 1.31067690e-08  4.17585855e-10  3.00000042e-01]
 [ 4.06976901e-02 -9.98147011e-01  2.74543524e-01]
 [ 4.15549316e-02 -9.98052657e-01  2.55233526e-01]
 [ 4.14286666e-02 -9.97952640e-01  2.35906288e-01]
 [ 4.13895845e-02 -9.97898340e-01  2.16574416e-01]
 [ 4.13812287e-02 -9.97